# Generated by Django 5.1.1 on 2024-09-22 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from django.contrib.auth.models import User

def create_owner(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('your_app_name', 'Profile')

    owner = User.objects.create(username='owner', email='owner@gmail.com', is_staff=True, is_superuser=True)
    owner.set_password('owner_password')  
    owner.save()

    Profile.objects.create(user=owner, role='owner')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('FR', 'Fresh Produce'), ('DA', 'Dairy'), ('BV', 'Beverages'), ('SN', 'Snacks'), ('CL', 'Cleaning Supplies'), ('PH', 'Pharmacy'), ('OT', 'Other')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_purchased', models.IntegerField()),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='purchase_history',
            field=models.ManyToManyField(through='retail_app.Purchase', to='retail_app.product'),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retail_app.product')),
            ],
        ),
    ]
