# Generated by Django 5.1.1 on 2024-09-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FR', 'Fresh Produce'), ('DA', 'Dairy'), ('BV', 'Beverages'), ('SN', 'Snacks'), ('CL', 'Cleaning Supplies'), ('PH', 'Pharmacy'), ('OT', 'Other')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
