# Generated by Django 5.1.1 on 2024-09-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media/products/'),
        ),
    ]
