# Generated by Django 5.1.1 on 2024-09-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail_app', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='smart_retail/retail_app/static/media'),
        ),
    ]
